DEF VAR pfilename-xml AS CHAR.

DEF VAR pacc-group-name AS CHAR FORMAT "x(100)".
DEF VAR pacc-group-parent-name AS CHAR FORMAT "x(100)".

DEF VAR pacc-ledger-name AS CHAR FORMAT "x(100)".
DEF VAR pacc-ledger-parent-name AS CHAR FORMAT "x(100)".

DEF VAR pvouchertype AS CHAR.
DEF VAR pvouchernumber AS CHAR.
DEF VAR pvoucherdate AS DATE.
DEF VAR pvoucherdate-txt AS CHAR.
DEF VAR pnarration AS CHAR.
DEF VAR pvchkey AS CHAR.
DEF VAR pguid AS CHAR.
DEF VAR premoteid AS CHAR.
DEF VAR ppartyledgername AS CHAR.
DEF VAR pledgername-debit1 AS CHAR.
DEF VAR pledgername-debit2 AS CHAR.
DEF VAR pledgername-debit3 AS CHAR.
DEF VAR pledgername-debit4 AS CHAR.
DEF VAR pledgername-debit5 AS CHAR.
DEF VAR pledgername-credit1 AS CHAR.
DEF VAR pledgername-credit2 AS CHAR.
DEF VAR pledgername-credit3 AS CHAR.
DEF VAR pledgername-credit4 AS CHAR.
DEF VAR pledgername-credit5 AS CHAR.
DEF VAR pledgeramount-debit1 AS DEC.
DEF VAR pledgeramount-debit2 AS DEC.
DEF VAR pledgeramount-debit3 AS DEC.
DEF VAR pledgeramount-debit4 AS DEC.
DEF VAR pledgeramount-debit5 AS DEC.
DEF VAR pledgeramount-credit1 AS DEC.
DEF VAR pledgeramount-credit2 AS DEC.
DEF VAR pledgeramount-credit3 AS DEC.
DEF VAR pledgeramount-credit4 AS DEC.
DEF VAR pledgeramount-credit5 AS DEC.
DEF VAR pvouchertotalamount AS DEC.

DEF VAR pcashbankledger AS CHAR.
DEF VAR peffectivedate AS DATE.
DEF VAR peffectivedate-txt AS CHAR.

DEF VAR pchequedate AS DATE.
DEF VAR pchequedate-txt AS CHAR.
DEF VAR ppaymentfovouring AS CHAR.
DEF VAR pbankpartyname AS CHAR.

DEF VAR palterid AS CHAR.
DEF VAR pmasterid AS CHAR.
DEF VAR pvoucherkey AS CHAR.

ASSIGN pacc-group-name = "My Debtors".
ASSIGN pacc-group-parent-name = "Accounts Receivable".

ASSIGN pacc-ledger-name = "Communication Expenses".
ASSIGN pacc-ledger-parent-name = "Indirect Expenses".

ASSIGN pfilename-xml = "C:\pvr\giph\tallylib\CreateVoucher.xml".


ASSIGN pvouchertype         = "Payment"
       pvouchernumber       = "CDV36462"
       pvoucherdate         = 10/31/19
       peffectivedate       = 10/31/19
       pchequedate          = 10/31/19
       pvoucherdate-txt     = STRING(YEAR(pvoucherdate),"9999") + STRING(MONTH(pvoucherdate),"99") + STRING(DAY(pvoucherdate),"99") 
       peffectivedate-txt   = STRING(YEAR(peffectivedate),"9999") + STRING(MONTH(peffectivedate),"99") + STRING(DAY(peffectivedate),"99") 
       pchequedate-txt      = STRING(YEAR(peffectivedate),"9999") + STRING(MONTH(peffectivedate),"99") + STRING(DAY(peffectivedate),"99") 
       ppartyledgername     = "UCPB C/A PHP 201120001328"
       pnarration           = "cdv36461 - PLDT"

/*   
       pvchkey              = "a9545bdc-3762-40ba-8917-ec660dcacc0e-00000052:000001d6"
       
       pguid                = "a9545bdc-3762-40ba-8917-ec660dcacc0e-00000052"
       premoteid            = "a9545bdc-3762-40ba-8917-ec660dcacc0e-00000052"
       */
      
       pvchkey              = "a9545bdc-3762-40ba-8917-ec660dcacc0e-00036462:000001d6"
       pguid                = "a9545bdc-3762-40ba-8917-ec660dcacc0e-00036462"
       premoteid            = "a9545bdc-3762-40ba-8917-ec660dcacc0e-00036462"


       pcashbankledger      = "UCPB C/A PHP 201120001328"
       palterid             = " 169"
       pmasterid            = " 82"
       pvoucherkey          = "187982128611798"


       pledgername-debit1    = "Communication Expenses"
       pledgeramount-debit1  = 3838.39 * -1
       
       pledgername-debit2    = "Input Vat @ 12%"
       pledgeramount-debit2  = 460.61 * -1

       pledgername-debit3    = ""
       pledgeramount-debit3  = 0
       pledgername-debit4    = ""
       pledgeramount-debit4  = 0
       pledgername-debit5    = ""
       pledgeramount-debit5  = 0


       pledgername-credit1    = "UCPB C/A PHP 201120001328"
       pledgeramount-credit1  = 4299.00
       ppaymentfovouring      = "Communication Expenses"
       pbankpartyname         = "Communication Expenses"
       pledgername-credit2    = ""
       pledgeramount-credit2  = 0
       pledgername-credit3    = ""
       pledgeramount-credit3  = 0
       pledgername-credit4    = ""
       pledgeramount-credit4  = 0
       pledgername-credit5    = ""
       pledgeramount-credit5  = 0

       pvouchertotalamount  = 0

    .
    


OUTPUT TO VALUE(pfilename-xml).

    PUT UNFORMATTED "<ENVELOPE>" SKIP.
    PUT UNFORMATTED " <HEADER>" SKIP.
    PUT UNFORMATTED "  <TALLYREQUEST>Import Data</TALLYREQUEST>" SKIP.
    PUT UNFORMATTED " </HEADER>" SKIP.
    PUT UNFORMATTED " <BODY>" SKIP.
    PUT UNFORMATTED "  <IMPORTDATA>" SKIP.
    PUT UNFORMATTED "   <REQUESTDESC>" SKIP.
    PUT UNFORMATTED "    <REPORTNAME>All Masters</REPORTNAME>" SKIP.
    PUT UNFORMATTED "   </REQUESTDESC>" SKIP.
    PUT UNFORMATTED "   <REQUESTDATA>" SKIP.
    PUT UNFORMATTED '    <TALLYMESSAGE xmlns:UDF="TallyUDF">' SKIP.
    
    /*
    RUN CreateAccGroup.
    RUN CreateLedger.
    */
    RUN CreatePaymentTrans.
    
    PUT UNFORMATTED "    </TALLYMESSAGE>" SKIP.
    PUT UNFORMATTED "   </REQUESTDATA>" SKIP.
    PUT UNFORMATTED "  </IMPORTDATA>" SKIP.
    PUT UNFORMATTED " </BODY>" SKIP.
    PUT UNFORMATTED "</ENVELOPE>" SKIP.

OUTPUT CLOSE.

OS-DELETE VALUE("C:\pvr\giph\tallylib\CreateVoucher-response.txt") NO-ERROR.
OS-COMMAND SILENT VALUE("C:\pvr\giph\tallylib\CreateVoucher.BAT").
OS-COMMAND NO-WAIT VALUE("C:\pvr\giph\tallylib\CreateVoucher-response.txt") NO-ERROR.



PROCEDURE CreateAccGroup.
    PUT UNFORMATTED '     <GROUP ACTION="Create" NAME="' pacc-group-name '">' SKIP.
    PUT UNFORMATTED "      <NAME.LIST>" SKIP.
    PUT UNFORMATTED "      <NAME>" pacc-group-name "</NAME>" SKIP.
    PUT UNFORMATTED "      </NAME.LIST>" SKIP.
    PUT UNFORMATTED "      <PARENT>" pacc-group-parent-name "</PARENT>" SKIP.
    PUT UNFORMATTED "      <ISSUBLEDGER>No</ISSUBLEDGER>" SKIP.
    PUT UNFORMATTED "      <ISBILLWISEON>No</ISBILLWISEON>" SKIP.
    PUT UNFORMATTED "      <ISCOSTCENTRESON>No</ISCOSTCENTRESON>" SKIP.
    PUT UNFORMATTED "     </GROUP>" SKIP.
END PROCEDURE.

PROCEDURE CreateLedger.
    PUT UNFORMATTED '     <LEDGER NAME="' pacc-ledger-name '" RESERVEDNAME="">' SKIP.
    PUT UNFORMATTED "      <CURRENCYNAME>p</CURRENCYNAME>" SKIP.
    PUT UNFORMATTED "      <PARENT>" pacc-ledger-parent-name "</PARENT>" SKIP.
    PUT UNFORMATTED "      <ISBILLWISEON>No</ISBILLWISEON>" SKIP.
    PUT UNFORMATTED "      <ISCOSTCENTRESON>Yes</ISCOSTCENTRESON>" SKIP.
    PUT UNFORMATTED "      <LANGUAGENAME.LIST>" SKIP.
    PUT UNFORMATTED '       <NAME.LIST TYPE="String">' SKIP.
    PUT UNFORMATTED "        <NAME>" pacc-ledger-name "</NAME>" SKIP.
    PUT UNFORMATTED "       </NAME.LIST>" SKIP.
    PUT UNFORMATTED "       <LANGUAGEID> 1033</LANGUAGEID>" SKIP.
    PUT UNFORMATTED "      </LANGUAGENAME.LIST>" SKIP.
    PUT UNFORMATTED "     </LEDGER>" SKIP.
END PROCEDURE.

PROCEDURE CreatePaymentTrans.

    /*PUT UNFORMATTED '     <VOUCHER REMOTEID="a9545bdc-3762-40ba-8917-ec660dcacc0e-00000052" VCHKEY="a9545bdc-3762-40ba-8917-ec660dcacc0e-0000aaf8:000001d6" VCHTYPE="' pvouchertype '" ACTION="Create" OBJVIEW="Accounting Voucher View">' SKIP.     */
    PUT UNFORMATTED '     <VOUCHER REMOTEID="' premoteid '" VCHKEY="' pvchkey '"VCHTYPE=" ' pvouchertype '" ACTION="Create" OBJVIEW="Accounting Voucher View">' SKIP.     
    PUT UNFORMATTED '      <OLDAUDITENTRYIDS.LIST TYPE="Number">' SKIP.
    PUT UNFORMATTED "       <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>" SKIP.
    PUT UNFORMATTED "      </OLDAUDITENTRYIDS.LIST>" SKIP.
    PUT UNFORMATTED "      <DATE>" pvoucherdate-txt "</DATE>" SKIP.                                 /***************/
    PUT UNFORMATTED "      <GUID>" pguid "</GUID>" SKIP.                                            /***************/
    PUT UNFORMATTED "      <NARRATION>" pnarration "</NARRATION>" SKIP.                             /***************/
    PUT UNFORMATTED "      <VOUCHERTYPENAME>" pvouchertype "</VOUCHERTYPENAME>" SKIP.               /***************/
    PUT UNFORMATTED "      <VOUCHERNUMBER>" pvouchernumber "</VOUCHERNUMBER>" SKIP.                 /***************/
    PUT UNFORMATTED "      <PARTYLEDGERNAME>" ppartyledgername "</PARTYLEDGERNAME>" SKIP.            /***************/
    PUT UNFORMATTED "      <CSTFORMISSUETYPE/>" SKIP.
    PUT UNFORMATTED "      <CSTFORMRECVTYPE/>" SKIP.
    PUT UNFORMATTED "      <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>" SKIP.
    PUT UNFORMATTED "      <PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW>" SKIP.
    PUT UNFORMATTED "      <VCHGSTCLASS/>" SKIP.
    PUT UNFORMATTED "      <DIFFACTUALQTY>No</DIFFACTUALQTY>" SKIP.
    PUT UNFORMATTED "      <ISMSTFROMSYNC>No</ISMSTFROMSYNC>" SKIP.
    PUT UNFORMATTED "      <ASORIGINAL>No</ASORIGINAL>" SKIP.
    PUT UNFORMATTED "      <AUDITED>No</AUDITED>" SKIP.
    PUT UNFORMATTED "      <FORJOBCOSTING>No</FORJOBCOSTING>" SKIP.
    PUT UNFORMATTED "      <ISOPTIONAL>No</ISOPTIONAL>" SKIP.
    PUT UNFORMATTED "      <EFFECTIVEDATE>" peffectivedate-txt "</EFFECTIVEDATE>" SKIP.             /***************/   
    PUT UNFORMATTED "      <USEFOREXCISE>No</USEFOREXCISE>" SKIP.
    PUT UNFORMATTED "      <ISFORJOBWORKIN>No</ISFORJOBWORKIN>" SKIP.
    PUT UNFORMATTED "      <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>" SKIP.
    PUT UNFORMATTED "      <USEFORINTEREST>No</USEFORINTEREST>" SKIP.
    PUT UNFORMATTED "      <USEFORGAINLOSS>No</USEFORGAINLOSS>" SKIP.
    PUT UNFORMATTED "      <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>" SKIP.
    PUT UNFORMATTED "      <USEFORCOMPOUND>No</USEFORCOMPOUND>" SKIP.
    PUT UNFORMATTED "      <USEFORSERVICETAX>No</USEFORSERVICETAX>" SKIP.
    PUT UNFORMATTED "      <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>" SKIP.
    PUT UNFORMATTED "      <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>" SKIP.
    PUT UNFORMATTED "      <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>" SKIP.
    PUT UNFORMATTED "      <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>" SKIP.
    PUT UNFORMATTED "      <EXCISEOPENING>No</EXCISEOPENING>" SKIP.
    PUT UNFORMATTED "      <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>" SKIP.
    PUT UNFORMATTED "      <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>" SKIP.
    PUT UNFORMATTED "      <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>" SKIP.
    PUT UNFORMATTED "      <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>" SKIP.
    PUT UNFORMATTED "      <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>" SKIP.
    PUT UNFORMATTED "      <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>" SKIP.
    PUT UNFORMATTED "      <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>" SKIP.
    PUT UNFORMATTED "      <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>" SKIP.
    PUT UNFORMATTED "      <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>" SKIP.
    PUT UNFORMATTED "      <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>" SKIP.
    PUT UNFORMATTED "      <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>" SKIP.
    PUT UNFORMATTED "      <ISISDVOUCHER>No</ISISDVOUCHER>" SKIP.
    PUT UNFORMATTED "      <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>" SKIP.
    PUT UNFORMATTED "      <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>" SKIP.
    PUT UNFORMATTED "      <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>" SKIP.
    PUT UNFORMATTED "      <GSTNOTEXPORTED>No</GSTNOTEXPORTED>" SKIP.
    PUT UNFORMATTED "      <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>" SKIP.
    PUT UNFORMATTED "      <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>" SKIP.
    PUT UNFORMATTED "      <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>" SKIP.
    PUT UNFORMATTED "      <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>" SKIP.
    PUT UNFORMATTED "      <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>" SKIP.
    PUT UNFORMATTED "      <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>" SKIP.
    PUT UNFORMATTED "      <ISCANCELLED>No</ISCANCELLED>" SKIP.
    PUT UNFORMATTED "      <HASCASHFLOW>Yes</HASCASHFLOW>" SKIP.
    PUT UNFORMATTED "      <ISPOSTDATED>No</ISPOSTDATED>" SKIP.
    PUT UNFORMATTED "      <USETRACKINGNUMBER>No</USETRACKINGNUMBER>" SKIP.
    PUT UNFORMATTED "      <ISINVOICE>No</ISINVOICE>" SKIP.
    PUT UNFORMATTED "      <MFGJOURNAL>No</MFGJOURNAL>" SKIP.
    PUT UNFORMATTED "      <HASDISCOUNTS>No</HASDISCOUNTS>" SKIP.
    PUT UNFORMATTED "      <ASPAYSLIP>No</ASPAYSLIP>" SKIP.
    PUT UNFORMATTED "      <ISCOSTCENTRE>No</ISCOSTCENTRE>" SKIP.
    PUT UNFORMATTED "      <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>" SKIP.
    PUT UNFORMATTED "      <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>" SKIP.
    PUT UNFORMATTED "      <ISBLANKCHEQUE>No</ISBLANKCHEQUE>" SKIP.
    PUT UNFORMATTED "      <ISVOID>No</ISVOID>" SKIP.
    PUT UNFORMATTED "      <ISONHOLD>No</ISONHOLD>" SKIP.
    PUT UNFORMATTED "      <ORDERLINESTATUS>No</ORDERLINESTATUS>" SKIP.
    PUT UNFORMATTED "      <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>" SKIP.
    PUT UNFORMATTED "      <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>" SKIP.
    PUT UNFORMATTED "      <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>" SKIP.
    PUT UNFORMATTED "      <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>" SKIP.
    PUT UNFORMATTED "      <ISVATDUTYPAID>No</ISVATDUTYPAID>" SKIP.
    PUT UNFORMATTED "      <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>" SKIP.
    PUT UNFORMATTED "      <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>" SKIP.
    PUT UNFORMATTED "      <ISDELETED>No</ISDELETED>" SKIP.
    PUT UNFORMATTED "      <CHANGEVCHMODE>No</CHANGEVCHMODE>" SKIP.
    PUT UNFORMATTED "      <ALTERID>" palterid "</ALTERID>" SKIP.                                           /***************/
    PUT UNFORMATTED "      <MASTERID>" pmasterid "</MASTERID>" SKIP.                                        /***************/
    PUT UNFORMATTED "      <VOUCHERKEY>" pvoucherkey "</VOUCHERKEY>" SKIP.                                  /***************/
    PUT UNFORMATTED "      <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>" SKIP.
    PUT UNFORMATTED "      <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "      <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "      <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "      <DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "      <SUPPLEMENTARYDUTYHEADDETAILS.LIST>      </SUPPLEMENTARYDUTYHEADDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "      <EWAYBILLDETAILS.LIST>      </EWAYBILLDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "      <INVOICEDELNOTES.LIST>      </INVOICEDELNOTES.LIST>" SKIP.
    PUT UNFORMATTED "      <INVOICEORDERLIST.LIST>      </INVOICEORDERLIST.LIST>" SKIP.
    PUT UNFORMATTED "      <INVOICEINDENTLIST.LIST>      </INVOICEINDENTLIST.LIST>" SKIP.
    PUT UNFORMATTED "      <ATTENDANCEENTRIES.LIST>      </ATTENDANCEENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "      <ORIGINVOICEDETAILS.LIST>      </ORIGINVOICEDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "      <INVOICEEXPORTLIST.LIST>      </INVOICEEXPORTLIST.LIST>" SKIP.
    PUT UNFORMATTED "      <ALLLEDGERENTRIES.LIST>" SKIP.
    PUT UNFORMATTED '       <OLDAUDITENTRYIDS.LIST TYPE="Number">' SKIP.
    PUT UNFORMATTED "        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>" SKIP.
    PUT UNFORMATTED "       </OLDAUDITENTRYIDS.LIST>" SKIP.
    PUT UNFORMATTED "       <LEDGERNAME>" pledgername-debit1 "</LEDGERNAME>" SKIP.                                /***************/
    PUT UNFORMATTED "       <GSTCLASS/>" SKIP.
    PUT UNFORMATTED "       <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>" SKIP.
    PUT UNFORMATTED "       <LEDGERFROMITEM>No</LEDGERFROMITEM>" SKIP.
    PUT UNFORMATTED "       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>" SKIP.
    PUT UNFORMATTED "       <ISPARTYLEDGER>No</ISPARTYLEDGER>" SKIP.
    PUT UNFORMATTED "       <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>" SKIP.
    PUT UNFORMATTED "       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>" SKIP.
    PUT UNFORMATTED "       <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>" SKIP.
    PUT UNFORMATTED "       <AMOUNT>" pledgeramount-debit1 "</AMOUNT>" SKIP.                                       /***************/
    PUT UNFORMATTED "       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>" SKIP.
    PUT UNFORMATTED "       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>" SKIP.
    PUT UNFORMATTED "       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <RATEDETAILS.LIST>       </RATEDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>" SKIP.
    PUT UNFORMATTED "       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "      </ALLLEDGERENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "      <ALLLEDGERENTRIES.LIST>" SKIP.
    PUT UNFORMATTED '       <OLDAUDITENTRYIDS.LIST TYPE="Number">' SKIP.
    PUT UNFORMATTED "        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>" SKIP.
    PUT UNFORMATTED "       </OLDAUDITENTRYIDS.LIST>" SKIP.
    PUT UNFORMATTED "       <LEDGERNAME>" pledgername-debit2 "</LEDGERNAME>" SKIP.                                         /***************/
    PUT UNFORMATTED "       <GSTCLASS/>" SKIP.
    PUT UNFORMATTED "       <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>" SKIP.
    PUT UNFORMATTED "       <LEDGERFROMITEM>No</LEDGERFROMITEM>" SKIP.
    PUT UNFORMATTED "       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>" SKIP.
    PUT UNFORMATTED "       <ISPARTYLEDGER>No</ISPARTYLEDGER>" SKIP.
    PUT UNFORMATTED "       <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>" SKIP.
    PUT UNFORMATTED "       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>" SKIP.
    PUT UNFORMATTED "       <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>" SKIP.
    PUT UNFORMATTED "       <AMOUNT>" pledgeramount-debit2 "</AMOUNT>" SKIP.                                               /***************/
    PUT UNFORMATTED "       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>" SKIP.
    PUT UNFORMATTED "       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>" SKIP.
    PUT UNFORMATTED "       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <RATEDETAILS.LIST>       </RATEDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>" SKIP.
    PUT UNFORMATTED "       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "      </ALLLEDGERENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "      <ALLLEDGERENTRIES.LIST>" SKIP.
    PUT UNFORMATTED '       <OLDAUDITENTRYIDS.LIST TYPE="Number">' SKIP.
    PUT UNFORMATTED "        <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>" SKIP.
    PUT UNFORMATTED "       </OLDAUDITENTRYIDS.LIST>" SKIP.
    PUT UNFORMATTED "       <LEDGERNAME>" pledgername-credit1 "</LEDGERNAME>" SKIP.                               /***************/
    PUT UNFORMATTED "       <GSTCLASS/>" SKIP.
    PUT UNFORMATTED "       <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>" SKIP.
    PUT UNFORMATTED "       <LEDGERFROMITEM>No</LEDGERFROMITEM>" SKIP.
    PUT UNFORMATTED "       <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>" SKIP.
    PUT UNFORMATTED "       <ISPARTYLEDGER>Yes</ISPARTYLEDGER>" SKIP.
    PUT UNFORMATTED "       <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>" SKIP.
    PUT UNFORMATTED "       <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>" SKIP.
    PUT UNFORMATTED "       <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>" SKIP.
    PUT UNFORMATTED "       <AMOUNT>" pledgeramount-credit1  "</AMOUNT>" SKIP.                                    /***************/
    PUT UNFORMATTED "       <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <BANKALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "        <DATE>" pvoucherdate-txt "</DATE>" SKIP.                                              /***************/
    PUT UNFORMATTED "        <INSTRUMENTDATE>" pchequedate-txt "</INSTRUMENTDATE>" SKIP.                           /***************/  
    PUT UNFORMATTED "        <NAME>80b5ca2c-72d1-4faa-95dc-7f18b275579c</NAME>" SKIP.
    PUT UNFORMATTED "        <TRANSACTIONTYPE>Cheque</TRANSACTIONTYPE>" SKIP.                                      /***************/
    PUT UNFORMATTED "        <PAYMENTFAVOURING>" ppaymentfovouring "</PAYMENTFAVOURING>" SKIP.                     /***************/
    PUT UNFORMATTED "        <CHEQUECROSSCOMMENT>A/c Payee</CHEQUECROSSCOMMENT>" SKIP.                             /***************/
    PUT UNFORMATTED "        <UNIQUEREFERENCENUMBER>4rHnRatSlmtwZwWR</UNIQUEREFERENCENUMBER>" SKIP.
    PUT UNFORMATTED "        <STATUS>No</STATUS>" SKIP.
    PUT UNFORMATTED "        <PAYMENTMODE>Transacted</PAYMENTMODE>" SKIP.                                          /***************/
    PUT UNFORMATTED "        <BANKPARTYNAME>" pbankpartyname "</BANKPARTYNAME>" SKIP.                              /***************/
    PUT UNFORMATTED "        <ISCONNECTEDPAYMENT>No</ISCONNECTEDPAYMENT>" SKIP.
    PUT UNFORMATTED "        <ISSPLIT>No</ISSPLIT>" SKIP.
    PUT UNFORMATTED "        <ISCONTRACTUSED>No</ISCONTRACTUSED>" SKIP.
    PUT UNFORMATTED "        <ISACCEPTEDWITHWARNING>No</ISACCEPTEDWITHWARNING>" SKIP.
    PUT UNFORMATTED "        <ISTRANSFORCED>No</ISTRANSFORCED>" SKIP.
    PUT UNFORMATTED "        <AMOUNT>" pledgeramount-credit1 "</AMOUNT>" SKIP.                                     /***************/
    PUT UNFORMATTED "        <CONTRACTDETAILS.LIST>        </CONTRACTDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "        <BANKSTATUSINFO.LIST>        </BANKSTATUSINFO.LIST>" SKIP.
    PUT UNFORMATTED "       </BANKALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>" SKIP.
    PUT UNFORMATTED "       <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "       <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "       <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "       <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>" SKIP.
    PUT UNFORMATTED "       <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <RATEDETAILS.LIST>       </RATEDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>" SKIP.
    PUT UNFORMATTED "       <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>" SKIP.
    PUT UNFORMATTED "       <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "       <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "      </ALLLEDGERENTRIES.LIST>" SKIP.
    PUT UNFORMATTED "      <PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>" SKIP.
    PUT UNFORMATTED "      <ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>" SKIP.
    PUT UNFORMATTED "      <GSTEWAYCONSIGNORADDRESS.LIST>      </GSTEWAYCONSIGNORADDRESS.LIST>" SKIP.
    PUT UNFORMATTED "      <GSTEWAYCONSIGNEEADDRESS.LIST>      </GSTEWAYCONSIGNEEADDRESS.LIST>" SKIP.
    PUT UNFORMATTED "      <TEMPGSTRATEDETAILS.LIST>      </TEMPGSTRATEDETAILS.LIST>" SKIP.
    PUT UNFORMATTED "     </VOUCHER>" SKIP.

END PROCEDURE.



/*
PROCEDURE CreateAccGroup.
    PUT UNFORMATTED '     <GROUP ACTION="Create" NAME="My Debtors">' SKIP.
    PUT UNFORMATTED "      <NAME.LIST>" SKIP.
    PUT UNFORMATTED "      <NAME>My Debtors</NAME>" SKIP.
    PUT UNFORMATTED "      </NAME.LIST>" SKIP.
    PUT UNFORMATTED "      <PARENT>Accounts Receivable</PARENT>" SKIP.
    PUT UNFORMATTED "      <ISSUBLEDGER>No</ISSUBLEDGER>" SKIP.
    PUT UNFORMATTED "      <ISBILLWISEON>No</ISBILLWISEON>" SKIP.
    PUT UNFORMATTED "      <ISCOSTCENTRESON>No</ISCOSTCENTRESON>" SKIP.
    PUT UNFORMATTED "     </GROUP>" SKIP.
END PROCEDURE.

PROCEDURE CreateLedger.
    PUT UNFORMATTED '    <LEDGER NAME="cccCommunication Expenses" RESERVEDNAME="">' SKIP.
    PUT UNFORMATTED "     <CURRENCYNAME>p</CURRENCYNAME>" SKIP.
    PUT UNFORMATTED "     <PARENT>Indirect Expenses</PARENT>" SKIP.
    PUT UNFORMATTED "     <ISBILLWISEON>No</ISBILLWISEON>" SKIP.
    PUT UNFORMATTED "     <ISCOSTCENTRESON>Yes</ISCOSTCENTRESON>" SKIP.
    PUT UNFORMATTED "     <LANGUAGENAME.LIST>" SKIP.
    PUT UNFORMATTED '      <NAME.LIST TYPE="String">' SKIP.
    PUT UNFORMATTED "       <NAME>cccCommunication Expenses</NAME>" SKIP.
    PUT UNFORMATTED "      </NAME.LIST>" SKIP.
    PUT UNFORMATTED "      <LANGUAGEID> 1033</LANGUAGEID>" SKIP.
    PUT UNFORMATTED "     </LANGUAGENAME.LIST>" SKIP.
    PUT UNFORMATTED "    </LEDGER>" SKIP.
END PROCEDURE.
*/

/************




************/
